credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$ry8j7c.cyCtv5X92THQxmeMTTnafUOr.pTzdb4T1B7v2p1DdayooW #abc # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: 2b$12$A9k.KJXV2/pjXTf0ve7.eualBqrpUug9Dt2Hze1zORDFx6/UosKKW #def # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com